target 'MyApp' do
    use_frameworks!
    pod 'MyFramework', '0.1.0', :source => "Users/vivekkasthuri/Desktop/workspace/cocoapods/MySpecs.git", project => "Users/vivekkasthuri/Desktop/workspace/cocoapods/MyApp/MyApp.xcodeproj"
end
