package com.music.analytics

object Event {

    //Clevertap
    const val CT_MUSIC_LAUNCHED: String = "music launched"
    const val CT_LANGUAGE_SELECTED: String = "music preferred language";
    const val CT_MUSIC_STARTED: String = "music started"
    const val CT_MUSIC_STOPPED: String = "music stopped"
    const val CT_MUSIC_FAILED: String = "music failed"
    const val CT_MUSIC_DETAILS_VIEWED: String = "music details viewed"
    const val CT_ADD_DELETE_FROM_PLAYLIST: String = "added deleted from playlist"
    const val CT_MUSIC_CLEAR_RECENT_SEARCH: String = "music clear recent search"
    const val CT_MUSIC_EXIT_EVENT: String = "music exit event"
    const val CT_MUSIC_SUBSCRIPTION_PACK_CHANGED: String = "music subscription pack changed"
    const val CT_MUSIC_LIVE_EVENTS_BOOKING: String = "music live events booking"
    const val CT_MUSIC_DOWNLOAD: String = "music download"
    const val CT_MUSIC_REGISTRATION_COMPLETED: String = "music registration completed"
    const val CT_MUSIC_FAVOURITED: String = "music favourited"
    const val CT_CREATED_DELETED_PLAYLIST: String = "created deleted Playlist"
    const val CT_MUSIC_SEARCHED: String = "music searched"
    const val CT_MUSIC_CLICKED: String = "music clicked"
    const val CT_MUSIC_TAB_VIEWED: String = "music tab viewed"
    const val CT_MUSIC_MOOD_SELECTOR: String = "music mood selector"
    const val CT_MUSIC_PROMOTIONAL_PLAYLIST: String = "music promotional playlist"
    const val CT_MUSIC_MENU = "music menu"
    const val CT_CALLERTUNES_SUBSCRIPTION = "callertunes subscription"
    const val CT_SET_CALLERTUNES = "set callertunes"
    const val CT_MUSIC_CATEGORY_VIEWED = "music category viewed"
    const val CT_MUSIC_PLAYBACK_SETTINGS = "music playback settings"
    const val CT_MUSIC_DOWNLOAD_PREFERENCES = "music download preferences"
    const val CT_MUSIC_DOWNLOAD_SETTINGS = "music download settings"
    const val CT_MY_MUSIC = "my music"
    const val CT_MUSIC_SUBSCRIPTION_BANNER_CLICKED = "music subscription banner clicked"
    const val CT_MUSIC_REPEAT = "music repeat"
    const val CT_MUSIC_SHUFFLE = "music shuffle"
    const val CT_MUSIC_LIVE_EVENTS = "music live Events"
    const val CT_MUSIC_TICKET_DETAILS_VIEWED = "music ticket details viewed"
    const val CT_MUSIC_EVENT_BOOKING_CANCELLATION = "music event booking cancellation"
    const val CT_MUSIC_SESSION_START = "music session start"
    const val CT_MUSIC_SESSION_END = "music session end"
    const val CT_MUSIC_PLAYER_ACTIONS = "music player actions"
    const val CT_MUSIC_ARTWORK_TAPPED = "music artwork tapped"
    const val CT_MUSIC_WELCOME_POPUP = "music welcome screen popup"
    const val CT_MUSIC_SUBSCRIBED = "music subscribed"
    const val CT_MUSIC_WEB_VIEW_PERFORMANCE = "music web view performance"
    const val CT_MUSIC_PAYMENT_GATEWAY = "music payment gateway"
    const val CT_MUSIC_AUTOCOMPLETE_RESULTS = "music autocomplete results"
    const val CT_MUSIC_PLAYER_QUALITY_SELECTED = "music player quality selected"
    const val CT_MUSIC_PLAY_ALL_CLICKED = "music play all clicked"
    const val CT_MUSIC_HOME_PAGE_SCROLL = "music home page scroll"
    const val CT_MUSIC_BUCKET_SWIPED = "music bucket swiped"
    const val CT_MUSIC_CORE_TAB_VIEWED = "music core tab viewed"
    const val CT_MUSIC_SUB_TAB_VIEWED = "music sub tab viewed"
    const val CT_MUSIC_RECHARGE_POPUP = "music recharge popup"
    const val CT_MUSIC_WELCOME_SCREEN_POPUP_APPEARED = "music welcome screen popup appeared"


    //Amplitude
    const val AM_MUSIC_CLICK = "hm_online_music_click"
    const val AM_LANGUAGE_SELECTED: String = "hm_music_lang_selected";
    const val AM_HOME_PG_EXPOSURE: String = "hm_home_pg_exposure"
    const val AM_HOME_PG_BACK_CLICKED: String = "hm_home_pg_back_clicked"
    const val AM_MUSIC_TAB: String = "hm_music_tab"
    const val AM_ARTWORK_TAPPED: String = "hm_artwork_tapped"
    const val AM_STREAM: String = "hm_stream"
    const val AM_STREAM_START: String = "hm_stream_start"
    const val AM_MY_MUSIC = "hm_my_music"
    const val AM_SEARCH_TAB_CLICKED = "hm_search_tab_clicked"
    const val AM_MUSIC_OFFLINED = "hm_music_offlined"
    const val AM_STREAM_FAILED = "hm_stream_failed"
    const val AM_VIDEO_PLAYER_PAUSE = "hm_video_player_pause"
    const val AM_VIDEO_PLAYER_PLAY = "hm_video_player_play"
    const val AM_VIDEO_PLAYER_SKIP_FORWARD = "hm_video_player_skip_forward"
    const val AM_VIDEO_PLAYER_SKIP_BACKWARD = "hm_video_player_skip_backward"
    const val AM_VIDEO_PLAYER_AUDIO_ACTION = "hm_video_player_audio_action"
    const val AM_VIDEO_PLAYER_BRIGHTNESS_ACTION = "hm_video_player_brightness_action"
    const val AM_VIDEO_PLAYER_VIDEO_QUALITY_SELECTED = "hm_video_player_video_quality_selected"
    const val AM_VIDEO_PLAYER_LOCK_TAPPED = "hm_video_player_lock_tapped"
    const val AM_VIDEO_PLAYER_BACK_TAPPED = "hm_video_player_back_tapped"
    const val AM_VIDEO_PLAYER_MUTE_BUTTON = "hm_Video_Player_mute_button"
    const val AM_AUDIO_PLAYER_PAUSE = "audio_player_pause"
    const val AM_AUDIO_PLAYER_PLAY = "audio_player_play"
    const val AM_AUDIO_PLAYER_SKIP_FORWARD = "audio_player_skip_forward"
    const val AM_AUDIO_PLAYER_SKIP_BACKWARD = "audio_player_skip_backward"
    const val AM_AUDIO_PLAYER_AUDIO_ACTION = "audio_player_audio_action"
    const val AM_AUDIO_PLAYER_QUALITY_SELECTED = "audio_player_quality_selected"
    const val AM_AUDIO_PLAYER_BACK_TAPPED = "audio_player_back_tapped"
    const val AM_WELCOME_SCREEN_POPUP = "hm_welcome_screen_popup"
    const val AM_CREATE_NEW_PLAYLIST = "hm_create_new_playlist"
    const val AM_REMOVE_PLAYLIST = "hm_remove_playlist"
    const val AM_ADDED_TO_PLAYLIST = "hm_added_to_playlist"
    const val AM_REMOVE_FROM_PLAYLIST = "hm_remove_from_playlist"
    const val AM_HOME_PG_SCROLL = "hm_home_pg_scroll"
    const val AM_BUCKET_SWIPED = "hm_bucket_swiped"
    const val AM_BUCKET_CLICKED = "hm_bucket_clicked"
    const val AM_MUSIC_LANG_SCREEN = "hm_music_lang_pref_exposure"
    const val AM_MYMUSIC_FAVOURITED = "hm_my_music_favourited";
    const val AM_WELCOME_SCREEN_POPUP_APPEARED = "hm_welcome_screen_popup_appeared"

}